### ISSUE TITLE
can u please explain about this project

### ISSUE THREAD

**Issue by Prasanna5432139** [LeslieCorrea/Android-Face-Recognition#1]

**Comment by LeslieCorrea** [comment]
Hi Prasanna,

This repository demonstrates face detection and person identification in an image from an Android device. This code explains taking a photo using a camera and sending it to the backend using REST API for processing, here Microsoft Project Oxford Face API was used. Now Microsoft has moved it to Azure Cognitive Services Vision, so you have to change the code accordingly. Please refer to https://azure.microsoft.com/en-in/services/cognitive-services/computer-vision/#product-overview for more details.

Thanks and Regards,
Leslie Correa
